spring:
    datasource:
        url: jdbc:mysql://192.168.2.147:3306/sda_gift?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: j987jklm
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          stat-view-servlet:
            login-password: "1qaz2wsx"
            login-username: admin
server:
  port: 8090
